[build]
builder = "NIXPACKS"

[deploy]
preDeployCommand = "npm run migrate && npm run seed:admin"
startCommand = "node src/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
